### ISSUE TITLE
bug(Dialog): Scrollbar shifts content to the left in Dialog

### ISSUE THREAD

**Issue by JohnathanWeisner** [narmi/design_system#1061]
### Component/Module
`Dialog`

### Screenshots (if applicable)
<img width="404" alt="Screenshot 2023-10-25 at 12 40 39 PM" src="https://github.com/narmi/design_system/assets/1588957/199b5259-c91c-46c0-9594-6282f6b0fa78">

### Reproduction Steps
Open a long Dialog that has a scrollbar.

### Expected Result
The scrollbar shouldn't shift content to the left.

### Actual Result
The scrollbar shifts content to the left.

### Additional Details / Context
Possible solution might be to have an observer looking for the scrollbar and if it is present remove that much padding from the right side of the Dialog.

(calculate scrollbar width with `offsetWidth - clientWidth`)

**Comment by JohnathanWeisner** [comment]
CC: @hillarypollak for visibility

**Comment by akdetrick** [comment]
## Dev plan

We already know when the dialog content container is overflowing, so we could use that to kill some right side padding on the dialog. The `isContentOverflowing` internal state variable should be enough to apply conditional padding to the right side of the content area or outer dialog

**Comment by reshav-abraham** [comment]
Note to self

```
        <Route path={["/", "/profile"]}>
          {(
            <UserSettingsProfilePage memberships={memberships} />
          )}
        </Route>
Do this in azul/components/settings/SettingsNavBar.tsx
```

**Comment by akdetrick** [comment]
This is Semantic-UI.

**Comment by akdetrick** [comment]
Will be handled by: https://github.com/narmi/banking/issues/40440

Closing.
