### ISSUE TITLE
[docs] Use `IconGallery` to replace our icon stories

### ISSUE THREAD

**Issue by akdetrick** [narmi/design_system#1070]
We currently use custom components to render icons in Storybook from our `selection.json`: https://github.com/narmi/design_system/blob/main/src/icons/Icons.stories.jsx

Now that we've upgraded to Storybook v7, we can use the IconGallery components instead for documenting the icons in NDS:
https://storybook.js.org/docs/react/api/doc-block-icongallery

## Definition of done

- `icons.stories.jsx` updated to use IconGallery built-in components from Storybook

**Comment by akdetrick** [comment]
@reshav-abraham might be a good one to pick up after the others

**Comment by akdetrick** [comment]
Updated the description to add some clarity. Not a top priority right now, but it would be nice to have this to make it easier to upgrade storybook later on.

**Comment by akdetrick** [comment]
Will be handled by Storybook v8 upgrade

**Comment by Vikrant-Khedkar** [comment]
great!
