### ISSUE TITLE
[Checkbox] Add indeterminate, disabled states; add size variant

### ISSUE THREAD

**Issue by akdetrick** [narmi/design_system#1081]
### New Hover / Focus state
We want to render an alpha circle shim around the checkbox without it taking up any space in document flow. Use alpha to color mix with any background the checkbox is on.

### Disabled state
As `disabled` boolean prop.

### Indeterminate state
The NDS `Checkbox` should support an indeterminate state. This is **not** a variant, but [a state represented in the rendered DOM](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes) that should be represented by a controlled boolean prop, `indeterminate`.

### Sizes
This design introduces a small size variant for our checkbox component.

## Design

cc @jlnguyen91 

https://www.figma.com/file/aqnNhzzRMJvKrMcJiVrMd4/NDS-WIP?type=design&node-id=38-771&mode=design&t=dJ8Q1TGiwkTs6rE4-0

<img width="193" alt="Screenshot 2023-11-13 at 2 18 14 PM" src="https://github.com/narmi/design_system/assets/231252/4b484368-b96d-4867-ace6-0de8abab1110">
<img width="464" alt="Screenshot 2023-11-13 at 2 18 06 PM" src="https://github.com/narmi/design_system/assets/231252/8173b92b-cba2-4600-8618-4983d2452332">

![Screenshot 2023-11-13 at 2 39 05 PM](https://github.com/narmi/design_system/assets/231252/6e206450-557e-4f79-a54d-db4645f3f8df)

## Definition of Done

- Checkbox hover effect updated to circle for `table` type
- Checkbox supports `indeterminate` prop
- Checkbox has a new variant, `table`, that has a circle hover effect and is smaller
- Checkbox supports `disabled` prop

**Comment by jlnguyen91** [comment]
@akdetrick this looks awesome! made a little prototype here to explain how users might interact with the parent checkbox: https://www.figma.com/file/aqnNhzzRMJvKrMcJiVrMd4/NDS-WIP?type=design&node-id=142-962&mode=design&t=4fwWFAuN2YNEuL6F-4

added a FormGroup section to explain how to handle group control components pulling from [here](https://mui.com/material-ui/react-checkbox/) (no changes to current behavior)

let me know if you have questions

**Comment by akdetrick** [comment]
**OPEN QUESTION**

How do we make the disabled normal checkbox look... more disabled?

**Comment by akdetrick** [comment]
Done, merged approved changes directly to main
