### ISSUE TITLE
[TruncatedAccount] lastFour is able to wrap

### ISSUE THREAD

**Issue by xiexiewenting** [narmi/design_system#1241]
### Component/Module

`TruncatedAccount`

### Screenshots (if applicable)
![Screenshot 2024-05-13 at 2 32 08 PM](https://github.com/narmi/design_system/assets/54218373/ee1b2714-a854-41d5-9cc1-d490ca1ad7a1)

### Reproduction Steps

Use a value of `lastFour` where there is a space (e.g. "33=0008 ($92,050.95)")

### Expected Result

`lastFour` is still 1 line

### Actual Result

`lastFour` wraps

**Comment by akdetrick** [comment]
We basically have two options here:

1. Compose truncation where this is used following the `lastFour` pattern, but with a min-width on the non-truncated section
2. Take `lastFourMinWidth` as a prop
