### ISSUE TITLE
overflowing Dialog content is blurred by footer

### ISSUE THREAD

**Issue by elliot-wilson** [narmi/design_system#1301]
### Component/Module

Dialog

### Screenshots (if applicable)

![image](https://uploads.linear.app/dfc544e9-324d-4096-bcda-63863fc9bb68/4fde551a-0925-4949-ad14-3810887c38a7/49123c4d-0254-41ab-a0a9-d2e13ffd4702?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2RmYzU0NGU5LTMyNGQtNDA5Ni1iY2RhLTYzODYzZmM5YmI2OC80ZmRlNTUxYS0wOTI1LTQ5NDktYWQxNC0zODEwODg3YzM4YTcvNDkxMjNjNGQtMDI1NC00MWFiLWEwYTktZDJlMTNmZmQ0NzAyIiwiaWF0IjoxNzI2MTcxOTkxLCJleHAiOjMzMjk2NzMxOTkxfQ.GykP3NeWuN7Sw0KFZIGLbQUMcYGYQtoua3aYRR_A8JQ)

### Reproduction Steps

```javascript
      
        isOpen
        title="Dialog"
        footer={
                kind="plain"
                label="Cancel"
              />
            
            
          
        }
      >
          
              
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
                * example, example
              
          
      
```

### Expected Result

Dialog content does not need additional padding to prevent blurring at bottom

### Actual Result

Dialog content is blurred by footer unless you add additional bottom padding

### Additional Details / Context

This is a placeholder issue until I do more of an investigation

**Comment by akdetrick** [comment]
## Proposed solution

There is a state variable that controls when the white box shadow should appear above the footer. This state variable is set by reading when the content area is scrollable.<br><br>We can use that same variable to add padding to the content area to prevent overlap of the lowermost content in the content area
