### ISSUE TITLE
[MultiselectCombobox] add support for MultiselectCombobox

### ISSUE THREAD

**Issue by elliot-wilson** [narmi/design_system#1312]
### Short Description

The current Combobox component only supports selecting a single item. We have designs -- e.g. filtering by segment on the new Manage Users filter panel -- that require selecting multiple items.

### Mockup

[https://www.figma.com/design/GerOQNpGS3PNlyrNKYSJrR/manage-users->-clients?node-id=5634-46732&t=RGWLbw76KJ729zRU-4](https://www.figma.com/design/GerOQNpGS3PNlyrNKYSJrR/manage-users-%3E-clients?node-id=5634-46732&t=RGWLbw76KJ729zRU-4)

![image](https://uploads.linear.app/dfc544e9-324d-4096-bcda-63863fc9bb68/408a7b57-4d22-4af1-87e2-20b3ad3239a5/aba9859d-e374-4f19-8822-69e1cabe7fe0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2RmYzU0NGU5LTMyNGQtNDA5Ni1iY2RhLTYzODYzZmM5YmI2OC80MDhhN2I1Ny00ZDIyLTRhZjEtODdlMi0yMGIzYWQzMjM5YTUvYWJhOTg1OWQtZTM3NC00ZjE5LTg4MjItNjllMWNhYmU3ZmUwIiwiaWF0IjoxNzI3ODE3Njc3LCJleHAiOjMzMjk4Mzc3Njc3fQ.TXjHAB31qPhj_upXmm-fMWl_zNeLJ13jXK6CHwmDnjk)

(This is used in coordination with checkboxes, but you can ignore them.)

### Responsibilities

**This component should be responsible for the following:**

* Should receive Items (vel sim) as children that can themselves contain children
* Should should show checkmarks on selected items
* Should receive `selectedItems` prop (vel sim)

**This component should NOT be responsible for...**

* Should not show tokens in input bar (or should be optional)
* 
* 

### Props Signature

```
<Component
  selectedItems={formData.segments}
  showTokens={false}
```

```
Component.propTypes = {
}
```

## ⚠️ Caution

Do **NOT** mix prop getters on the trigger element between `useMultipleSelection` and `useCombobox`. <br><br>The multiple selection hook should only be responsible for managing selected items. The input element should only receive prop getters from the `useCombobox` hook.

**Comment by akdetrick** [comment]
@elliot Do we know how many core segments there might be in the list?<br><br>This may be best handled with a text input and a list of `Checkbox` components that share a common state for filtering.<br><br>@jlnguyen91 It looks like the checkboxes filtered from search are displayed right under the input instead of in a popover - does that sound right?

**Comment by elliot-wilson** [comment]
It's not out of the question for there to be 30+ segments.

For now, we're using a Combobox + list of Checkboxes with a shared state for now: https://github.com/narmi/banking/blob/78a0db2aaa1144da9b16dcdb1b543d5bcfe95b35/staff/src/pages/users/users_list/FilterPanel.tsx#L146-L206. The checkboxes aren't really a problem here; we're more looking to expand what the Combobox can do.

Basically, we want it to behave like the NDS MultiSelect, but without the chips indicating the current selection, and _with_ the ability to type in the input box to filter the results.

**Comment by akdetrick** [comment]
Thanks!<br>@jlnguyen91 My assumption is that if we don't want the tokens from `MultiSelect`, we want the checkboxes in the popover to be the only indication of selection, or just comma separated text in the input value?
