### ISSUE TITLE
[Icons] Center non-Feather icons to match Feather's spacing

### ISSUE THREAD

**Issue by wrbrand** [narmi/design_system#183]
Our non-Feather icons are noticeably a little bigger than their Feather brethren:
![Screen Shot 2021-09-03 at 3 07 21 PM](https://user-images.githubusercontent.com/2448018/132054867-106f0ff8-5d21-4556-878a-ff155883c7df.png)
(Feather above, Material below)

I think this should just be a matter of resizing them in Icomoon so that they have a grid square of spacing around the sides, as the Feather icons do.

**Comment by akdetrick** [comment]
### Proposed solution

Standardize 24px canvas/grid for all icons via icomoon (except for outliers like venmo logo)

**Comment by wrbrand** [comment]
Closing in favor of https://github.com/narmi/design_system/issues/760.
