### ISSUE TITLE
[Components] Add Icon Input

### ISSUE THREAD

**Issue by wrbrand** [narmi/design_system#186]
The input used for search inputs is 40px tall, rather than 48px, never has a floating label, and might have a slightly different icon treatment than general TextInputs. We should create a new component to accommodate this, and add a story to demonstrate.

Ideally, this should be composable with the Dropdown component for this usage (from the style guide):
![Screen Shot 2021-09-03 at 3 19 56 PM](https://user-images.githubusercontent.com/2448018/132056141-f74bbf20-90ec-4c92-9126-d1412ffb9c1d.png)

**Comment by akdetrick** [comment]
likely needs to be broken into two tickets:

1. add icon prop to `DropdownTrigger`
2. add icon support to `TextInput`

**Comment by akdetrick** [comment]
Covered by `TextInput`
