### ISSUE TITLE
[Card] fix: title icon should be vertically centered 

### ISSUE THREAD

**Issue by agreatscott** [narmi/design_system#281]
![image](https://user-images.githubusercontent.com/4285085/138799565-90ba2cd8-c7f7-42bc-94b0-1c5a7995158f.png)

The icon in the title of the Card component is not centered vertically with the header text

**Comment by akdetrick** [comment]
won't do; the `Card` component is deprecated. The `ContentCard` component gives consumers full rendering control of the contents of the card
