### ISSUE TITLE
[Card] Audit border styles 

### ISSUE THREAD

**Issue by agreatscott** [narmi/design_system#324]
Received this feedback from design review. Opened this ticket because the border is currently 1px, but has a box-shadow. 

> Outline for hover looks too big. Should be 2px, looks like it’s maybe 3px? Just drop it down one

(orginally reported https://github.com/narmi/banking/issues/12513)

**Comment by akdetrick** [comment]
Won't do - `Card` is now deprecated. The `ContentCard` component handles this responsibility moving forward
