### ISSUE TITLE
[Docs] Publish a codepen with NDS examples

### ISSUE THREAD

**Issue by akdetrick** [narmi/design_system#435]
We need working examples to show how components and classes can be composed together to build a UI.

Let's publish a codepen with a directory of examples, so they can be linked to via the "run from module" feature.

## Why

- Downshift has similar documentation that has been very helpful.
- This repo would also serve as an example consumer of NDS in an environment we don't have to maintain.

## TODO:

- Create a new repo under narmi org, `design-system-examples`
- Set up a codesandbox using the "import from repo" feature
- Build at least 2 examples

**Comment by akdetrick** [comment]
Adding `BAO` label as this will be important for demonstrating how to compose grey cards from new helper classes.

**Comment by edakrong** [comment]
@akdetrick going to remove your assignment for now until we move this into "On Deck" for a milestone

**Comment by akdetrick** [comment]
Putting this back in the backlog; less important than other features we're working on.

**Comment by akdetrick** [comment]
Nobody is asking for this; going to close for now
