### ISSUE TITLE
[CI] Add license check via GitHub Actions to ensure dependencies use approved licenses

### ISSUE THREAD

**Issue by chris-griffin** [narmi/design_system#456]
We should run a CI check on PRs to ensure that we do not introduce a dependency without an approved license

Resources:

https://medium.com/@fokusman/the-easiest-way-to-check-all-your-npm-dependency-licenses-753075ef1d9d
https://github.com/tangro/actions-license-check

**Comment by reshav-abraham** [comment]
something of the sort works pretty well
`license-checker --onlyAllow 'MIT'; 'Apache-2.0'`

**Comment by reshav-abraham** [comment]
Notes from Amy:
What is the timeline? Do we want this done by the end of the year?
What you’re looking for from a notice/checklist perspective?

**Comment by akdetrick** [comment]
The scope of this ticket is to make sure we don't use any new vendors that don't comply with the licenses we already have in NDS.

For legal guidance, I filed a follow up ticket as that decision would apply to Narmi OSS practices more generally:
https://github.com/narmi/banking/issues/41618
