### ISSUE TITLE
Modal margins

### ISSUE THREAD

**Issue by thejinghao** [narmi/design_system#498]
### Component/Module
Modal

### Reproduction Steps
Submit duplicate bill pay

### Expected Result
![image](https://user-images.githubusercontent.com/26890187/146617070-931e653e-3457-4a71-8404-e5878963e5f7.png)

### Actual Result
![image](https://user-images.githubusercontent.com/26890187/146617178-03083f04-6839-4167-b881-d804d07fd23a.png)

### Additional Details / Context
- Remove top margin on form-section header
- Bottom margin to 8px on form-section header
- Remove bottom margin on div

**Comment by akdetrick** [comment]
Moving this issue to `banking`.

This is using the deprecated `Modal` component with the extra margin being applied in `banking`. Changing this to an NDS `Dialog` would solve the issue as it doesn't allow custom styling/spacing.
