### ISSUE TITLE
Incorrect documentation for CheckBox component 

### ISSUE THREAD

**Issue by agreatscott** [narmi/design_system#521]
### Component/Module

Storybook / Docs 

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/4285085/149638823-9ea98b52-75d6-4fcd-821c-3244c3141bfa.png)

### Reproduction Steps

The NDS checkbox component is exported as `CheckBox` but the documentation and storybook lists it as `Checkbox` including in same code

### Expected Result

Documentation should match how code should be used

**Comment by akdetrick** [comment]
We will rename `CheckBox` to `Checkbox` in then next major release.

**Comment by akdetrick** [comment]
fixed
