### ISSUE TITLE
formatDate does not work on some date formats

### ISSUE THREAD

**Issue by agreatscott** [narmi/design_system#555]
### Component/Module

formatters

### Reproduction Steps

call `formatDate` with value `2021-10-04`

### Expected Result

output `10/4/21`

### Actual Result

errors on `invalid date value`

**Comment by akdetrick** [comment]
Might be due to passing in a string instead of a `Date` object. The following assertion passes in `master`:

```js
const actual = formatDate(new Date('2021-10-4'), style);
const expected = "10/4/21";
expect(actual).toEqual(expected);
```

**Comment by akdetrick** [comment]
Works if passing a native date object as expected - closing
