### ISSUE TITLE
formatNumber does not properly format fraction percentages 

### ISSUE THREAD

**Issue by agreatscott** [narmi/design_system#556]
### Component/Module

formatters 

### Reproduction Steps

call `formatNumber` with input of `0.0023` and style of `percent` 

### Expected Result

`0.23%`

### Actual Result

`0%`

### Additional Details / Context

similarly `0.0325` should be `3.25%` but is instead shown as `0.03%`

**Comment by akdetrick** [comment]
For percentages, `formatNumber` is expecting a number representing calculated percentage, which is probably the wrong way to handle this. Submitting a PR that changes percentage formatter behavior to match `Intl.NumberFormat`

<img width="706" alt="Screen Shot 2022-01-31 at 1 13 06 PM" src="https://user-images.githubusercontent.com/231252/151849502-dbf38917-ffa9-4e82-bcaf-f0b5e4928690.png">
