### ISSUE TITLE
[Dropdown] Allow component to be a Controlled Component

### ISSUE THREAD

**Issue by space-cadet-josue** [narmi/design_system#580]
As it stands, the inner value for the Dropdown components is inaccessible because the component is uncontrolled. There are use cases when a developer/user wants to clear the selection from the Dropdown and have the component essentially "reset" both its value and its label, however this use case is impossible to achieve without wiring up the inner value to State (i.e. converting this component into a controlled component).

Suggestion: Expose the `value` prop from the inner `TextInput` component

**Comment by akdetrick** [comment]
Thanks for filing an issue; we would like all interactive components to at least have the option to be fully controlled, so this proposed change makes sense.

We'll aim to merge the change before the next major version is released.

**Comment by akdetrick** [comment]
@space-cadet-josue The `Dropdown` component is now deprecated. For a select dropdown UI, use the `Select` component moving forward.

The PR linked to this issue will add a `value` prop to `Select` to enable a fully controlled component.
