### ISSUE TITLE
Additional icons

### ISSUE THREAD

**Issue by kylekennedy6** [narmi/design_system#710]
Looks like we need some more icons to address some additional requests/legacy icons. I've attached SVG's of most of them if that helps!

`meter`
![credit score](https://user-images.githubusercontent.com/50111807/167032531-6cedd5e4-cffd-46e8-a6ef-242ba41821c6.svg)
`piggy-bank-outline` (currently we only have the filled version)
![clarity_savings-line](https://user-images.githubusercontent.com/50111807/167032641-0a13c561-aab7-4ba2-a7d0-2231d0b4f768.svg)
`money-bag`
![healthicons_money-bag-outline](https://user-images.githubusercontent.com/50111807/167032584-13b41234-d462-4809-9b35-7bdfdf3f255a.svg)
`shop`
![carbon_store](https://user-images.githubusercontent.com/50111807/167032520-1bc432bf-7bf0-407c-80f7-07145c818c7e.svg)
`trophy`
![ant-design_trophy-outlined](https://user-images.githubusercontent.com/50111807/167032675-838f64cb-9263-4fa4-baa3-b77468f9226d.svg)
`calculator`
(don't have an example of this one)

**Comment by akdetrick** [comment]
@kylekennedy6 It looks like our icon set has adequate coverage for most of these now. Can we close this ticket?

**Comment by kylekennedy6** [comment]
> @kylekennedy6 It looks like our icon set has adequate coverage for most of these now. Can we close this ticket?

absolutely!
