### ISSUE TITLE
[formatNumber] Support signDisplay option

### ISSUE THREAD

**Issue by ejrb** [narmi/design_system#736]
Money increments and decrements, such as in transaction lists, should be signed for both +ve and -ve values:

![Screen Shot 2022-05-26 at 10 41 33 AM](https://user-images.githubusercontent.com/5270155/170511555-21cac0e4-bbbc-46d9-be77-6943d5f5ebca.png)

`formatNumber` should support this option

### Technical details
- Intl.NumberDisplay supports this via the signDisplay  option with either `"always"` or `"exceptZero"` ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat))

**Comment by reshav-abraham** [comment]
closed via https://github.com/narmi/design_system/pull/1042
