### ISSUE TITLE
[Dialog] "X" design fixes

### ISSUE THREAD

**Issue by xiexiewenting** [narmi/design_system#764]
- The `X` is in the wrong spot (should be 16px from either edge)
- should be NDS black (is grey)
- looks a little small (is supposed to be 24 x 24 with the feather icon). The edges of the "x" are also not rounded but pointed so potentially not using the right icon (which has rounded edges).

the current `X`
<img width="114" alt="Screen Shot 2022-06-21 at 1 11 39 PM" src="https://user-images.githubusercontent.com/67279820/174859822-e4c198ff-d02d-4f00-ac79-4d1aed927f65.png">

the design's `X`
<img width="85" alt="Screen Shot 2022-06-24 at 2 47 45 PM" src="https://user-images.githubusercontent.com/54218373/175646736-a9735511-7a5a-4699-b97d-a953c6941a32.png">

sample dialog from a design
<img width="493" alt="Screen Shot 2022-06-21 at 1 24 43 PM" src="https://user-images.githubusercontent.com/67279820/174860679-90fcde4b-7266-4eb5-ab62-add4156b8327.png">

**Comment by akdetrick** [comment]
This is due to a feather icons update since design originally pulled icons into figma
