### ISSUE TITLE
Tool Tip pointer should be curved

### ISSUE THREAD

**Issue by reshav-abraham** [narmi/design_system#774]
### Component/Module
The ToolTip pointer should be curved. Looks like the border-radius should be adjusted as well

### Expected Result
<img width="688" alt="Screen Shot 2022-07-08 at 9 09 29 AM" src="https://user-images.githubusercontent.com/23458204/177998211-f889db1a-63a8-44c6-b841-c711dda26b16.png">

### Actual Result
<img width="710" alt="Screen Shot 2022-07-08 at 9 08 56 AM" src="https://user-images.githubusercontent.com/23458204/177998186-fdf4536d-37a1-4f47-87a5-31644e96a50e.png">

**Comment by akdetrick** [comment]
Changes will be handled in #858
