### ISSUE TITLE
[Toggle] Label styling is incorrect and not customizable 

### ISSUE THREAD

**Issue by agreatscott** [narmi/design_system#782]
### Component/Module

`<Toggle>`

### Additional Details / Context

It's been requested by design that the label font styling be determined on a per-instance basis on not be consistent across all `<Toggle>` instances. Suggestions are to either pull out the label from this component or allow prop(s) to be passed in to customize the styling.

**Comment by akdetrick** [comment]
## Planned changes

- When `label` is passed, render it as bold
- For non-bolded labels, consumers can use a [Toggle custom label](https://narmi.github.io/design_system/?path=/docs/components-toggle--with-custom-label)

**Comment by akdetrick** [comment]
Not making any code changes for this as `Toggle` already supports a [custom label](https://narmi.github.io/design_system/?path=/docs/components-toggle--with-custom-label).

There is no design intention for a "default" label styling for `Toggle`, so we can leave this component as-is for now until a consistent pattern emerges
