### ISSUE TITLE
[ContentCard] Allow customizable radius on ContentCard

### ISSUE THREAD

**Issue by francesbhughes** [narmi/design_system#825]
### Short Description

Current ContentCard variants have a radius of 4px, but we need to be able to accommodate an 8px radius. We should allow the radius to be an optional prop on ContentCard so it can be set to 8px in necessary places. 

### Mockup
https://www.figma.com/file/7o3se9SreiPKG4QWpGsAxg/BAO?node-id=2%3A14277

**Comment by akdetrick** [comment]
The `radius` prop should take a size in this format: https://github.com/narmi/design_system/blob/main/contributing/naming-conventions.md#size
