### ISSUE TITLE
Select Component breaks if initial value is an empty string.

### ISSUE THREAD

**Issue by madmonkey1995** [narmi/design_system#830]
### Component/Module
Select
### Reproduction Steps
Create a component with the exact code shown in the example on Storybook for a Controlled Select Component. Below:
`export default function MySelect() {
  const [value, setValue] = useState(null);
  return (
    <>
      <Select label="Account" value={value} onChange={(v) => setValue(v)}>
        <Select.Item value="checking1234">Checking (1234)</Select.Item>
        <Select.Item value="savings4321">Savings (4321)</Select.Item>
      </Select>
      <div className="margin--top">
        <Button
          label="Clear selection"
          kind="negative"
          onClick={() => {
            setValue(null);
          }}
        />
      </div>
    </>`
### Expected Result
Dropdown should render
### Actual Result
Component breaks
### Additional Details / Context
TypeError: Cannot read properties of undefined (reading 'value')
Replacing null with an empty string results in the same behavior.

**Comment by akdetrick** [comment]
@madmonkey1995 It looks like this is no longer an issue as of version `2.27.2`. My recommendation would be to upgrade the `@narmi/design_system` to the latest version, or at least `2.27.2`.
