### ISSUE TITLE
[Checkbox] Don't show outline on focused checkbox

### ISSUE THREAD

**Issue by kylekennedy6** [narmi/design_system#869]
related to narmi/banking#26643

Design has requested that we not show the outline here when a checkbox is checked. It seems this can be accomplished by removing the following line:
https://github.com/narmi/design_system/blob/a0da57adf2b9f1f6c7c623a43558c807fff5e055/src/Checkbox/index.scss#L58

#### Existing:
<img width="68" alt="Screenshot 2023-01-20 at 11 55 34 AM" src="https://user-images.githubusercontent.com/50111807/213757363-5c7e74d6-b17f-4ef8-ba58-699f5e6a37dd.png">

#### Desired:
<img width="53" alt="Screenshot 2023-01-20 at 11 58 58 AM" src="https://user-images.githubusercontent.com/50111807/213758080-51b5bdfe-5dbd-4126-bd8b-478d81b343a5.png">

**Comment by akdetrick** [comment]
@hillarypollak I'd recommend against this for accessibility reasons unless there's another visual indication of focus we had in mind. When navigating via keyboard, you need to be able to see which checkbox is currently focused

**Comment by kylekennedy6** [comment]
closing for now pending Hillary's comment

**Comment by hillarypollak** [comment]
ah i just mean that the focused state is fine when you're focused but once you click it, it shouldn't stay focused--it should go to selected state
