### ISSUE TITLE
"check-circle" icon check should be 1px wide

### ISSUE THREAD

**Issue by kylekennedy6** [narmi/design_system#872]
I don't have a ton of familiarity with how we build our icons, but @hillarypollak pointed out that the check mark in the check-circle & check-square are too wide. Would recommend syncing with her before taking on this ticket.

<img width="106" alt="Screenshot 2023-01-20 at 12 47 39 PM" src="https://user-images.githubusercontent.com/50111807/213771046-496956d7-dd47-4131-960e-978ca37ce77c.png">
<img width="131" alt="Screenshot 2023-01-20 at 12 49 50 PM" src="https://user-images.githubusercontent.com/50111807/213790083-04d79d4b-fbbb-46fc-96f0-a46f015b4afe.png">

**Comment by akdetrick** [comment]
Related to feather icons versioning (NDS uses latest; design had an older set)
