### ISSUE TITLE
[Select] Update selection color

### ISSUE THREAD

**Issue by akdetrick** [narmi/design_system#910]
Per design: The hover/selection state for select items should be 5% subdued brand color

see also: https://www.notion.so/narmi/First-IB-Design-QA-f751c057241e4031a9e9db636c2a6dba

**Comment by xiexiewenting** [comment]
We are correctly using the brand color: https://github.com/narmi/design_system/blob/a96e81ca4d16593093e2e67abec4b090581b7e7c/src/Select/index.scss#L29-L32

The issue is merely that `--theme-rgb-primary` isn't being properly set in AO, so going to fix the issue there!
