### ISSUE TITLE
[Icon] update `eye-off` icon

### ISSUE THREAD

**Issue by xiexiewenting** [narmi/design_system#927]
It currently looks like:

![Screen Shot 2023-05-02 at 1 52 12 PM](https://user-images.githubusercontent.com/54218373/235746816-971bae18-2b61-4bcf-8a16-22d53c356f2c.png)

It should look like:

![Screen Shot 2023-05-02 at 1 52 08 PM](https://user-images.githubusercontent.com/54218373/235746831-1a018d81-c2d2-4cf6-83df-691f40a50c89.png)

**Comment by akdetrick** [comment]
@hillarypollak Do we have an SVG asset for the "eye off" icon? We may want to get a fresh asset for the "eye on" asset as well, so the stroke thickness matches up correctly

**Comment by hillarypollak** [comment]
They're both the Feather icons one but lemme know if you need the asset

**Comment by akdetrick** [comment]
@hillarypollak I'm finally getting back to this and it looks like we have the most up to date `eye-off` shape from feather:
https://feathericons.com/?query=eye-off

Do you have something in figma that you can export an SVG from?

**Comment by hillarypollak** [comment]
![eye-off](https://github.com/narmi/design_system/assets/67279820/2a51d180-ad01-4bcb-93c6-44413f67bae0)

**Comment by akdetrick** [comment]
Looks like Feather has changed icons since we originally downloaded the set for use in designs. For now, this is a "wont fix" per design
