### ISSUE TITLE
[Tooltip] Allow the Tooltip component to be a controlled component. 

### ISSUE THREAD

**Issue by JohnathanWeisner** [narmi/design_system#944]
In https://github.com/narmi/banking/issues/33260 we need a controlled Tooltip component so that we can only open the `Tooltip` on the click of table row and then close the `Tooltip` when we stop hovering over the row.

There is no way to currently reproduce this behavior with the `Tooltip` component.
A new optional property called `isOpen` or `open` should be added.

**Comment by cs-paz** [comment]
@JohnathanWeisner I see this issue should be closed out by https://github.com/narmi/design_system/pull/945

I'm closing out this issue - feel free to reopen if needed
