### ISSUE TITLE
[dialog] responsive width being cut off

### ISSUE THREAD

**Issue by xiexiewenting** [narmi/design_system#999]
### Component/Module

Dialog

### Screenshots (if applicable)

![Screenshot 2023-08-15 at 8 11 55 PM](https://github.com/narmi/design_system/assets/54218373/c6cace2c-94ce-45d1-9b79-eeae2d757b91)

### Reproduction Steps

Open a dialog in https://narmi.github.io/design_system/?path=/docs/components-dialog--overview on your phone

### Expected Result

The dialog fits within the screen

### Actual Result

The dialog edges are being cut off

### Additional Details / Context

The passed in `width` prop (which has a default of 500px) 
https://github.com/narmi/design_system/blob/2bb36bb5e18c1431dc4bb27670ae045d72ebda20/src/Dialog/index.js#L86 is overriding

https://github.com/narmi/design_system/blob/2bb36bb5e18c1431dc4bb27670ae045d72ebda20/src/Dialog/index.scss#L50

**Comment by akdetrick** [comment]
We may want to try `matchMedia` here to conditionally add the prop only at "s" viewports and larger
